### ISSUE TITLE
[Feature Request] del.dog upload 

### ISSUE THREAD

**Issue by hjyoung1** [syberia-project/platform_frameworks_base#18]
I don't know if this is correct place to post this. But i don't use telegram so this is the only place i found to post.
Please add this del.dog upload crash logs feature. 
https://github.com/PotatoProject/frameworks_base/blob/a5e0f8bf1b2f9944632eb80745e87d629460f6f4/core/java/com/android/internal/util/DogbinUtils.java

**Comment by blinoff82** [comment]
Sorry, this will not be added.
